export const projects = [
    {
        id: 1,
        title: 'Mauve',
        path: 'mauve1.png',
        description: 'Mauve is a project made for a local make-up company.',
        description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
        site: 'mauve.pl',
    },
    {
      id: 2,
      title: 'ZTP Kraków',
      path: 'ztp1.png',
      description: 'ZTP Kraków is a project made as part of university classes.',
      description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
      site: '',
    },
    {
      id: 3,
      title: 'AN-BUD',
      path: 'an-bud1.png',
      description: 'AN-BUD is a website made for a local renovation contractor.',
      description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
      site: 'an-bud.net',
    },
    {
      id: 4,
      title: 'Hangman Game',
      path: 'hangman1.png',
      description: 'The hangman game is a browser game that I made as part of learning JavaScript',
      description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
      sute: '',
    },
    {
      id: 5,
      title: 'Mauve',
      path: 'mauve1.png',
      description: 'Mauve is a project made for a local make-up company.',
      description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
      site: 'mauve.pl',
    },
    {
      id: 6,
      title: 'Mauve',
      path: 'mauve1.png',
      description: 'Mauve is a project made for a local make-up company.',
      description2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum nulla officia, excepturi, neque assumenda quasi quisquam est corporis dignissimos ducimus delectus et dolore? Praesentium itaque accusamus, repellendus eligendi minima architecto ipsa fugiat ducimus culpa corrupti illum consequatur tempora maxime. Asperiores, ut. Corrupti, excepturi. Inventore suscipit magni adipisci sint animi delectus eligendi cum totam aut quos, sit neque eos esse autem exercitationem saepe incidunt odio officia laborum facere. Aperiam inventore deserunt ab dolorem eligendi, assumenda fugiat repellendus vitae odio aut delectus rerum maxime magnam, repudiandae alias totam nam ea a vel blanditiis quae. Voluptas quaerat animi nobis nostrum amet rerum commodi natus corrupti porro doloremque velit numquam quasi assumenda ipsum odit aliquid, illum sed, voluptatibus laudantium eos! Asperiores debitis odio eius totam obcaecati perferendis quis praesentium ut repellat laborum molestias quibusdam mollitia, dicta saepe laudantium quam, enim inventore iure! Magni pariatur dicta deleniti doloribus animi, vel labore voluptatum provident quisquam, exercitationem expedita cumque, quidem dignissimos id aut! Excepturi autem enim corrupti soluta ab quam doloribus! Laboriosam soluta officia aspernatur eos necessitatibus, vel expedita facere accusamus! Facere doloremque quia ea ab repellat labore itaque repudiandae quo. Velit expedita illum quam maiores accusantium, placeat voluptates cum suscipit facilis labore, natus voluptate aperiam! Dolorem!',
      site: 'mauve.pl',
    },
];

export const items = [
    {
        id: 1,
        title: 'React',
        path: 'React-icon.png',
        description: 'React is a JavaScript library for creating user interfaces (UI) in web applications. React was created by Facebook and is widely used by developers to create dynamic websites, web and mobile applications. React lets you create reusable UI components in different parts of your application, making it easier to develop and maintain your code. React uses a virtual DOM (Document Object Model) to render the UI faster and reduce the amount of work the browser has to do.',
        level: 'Beginner',
    },
    {
        id: 2,
        title: 'JavaScript',
        path: 'javascript.png',
        description: 'JavaScript is a dynamic programming language that is commonly used to create interactive websites and web applications. JavaScript is also often used on the server side, for example in the Node.js environment, to create web applications based on this language. JavaScript allows you to create interactive elements on a website, such as animations, visual effects, page refreshes without reloading, forms, and much more. It easily integrates with other languages ​​such as HTML and CSS, so you can create websites that are both visually appealing and functional.',
        level: 'Beginner',
    },
    {
        id: 3,
        title: 'HTML5',
        path: 'html5.png',
        description: 'HTML is a markup language used to create web pages. It allows developers to add content, images, links and more to web pages, as well as define their structure and layout. HTML is used by most websites around the world.',
        level: 'Junior',
    },
    {
        id: 4,
        title: 'CSS3',
        path: 'css3.png',
        description: 'CSS is a style language used to describe the appearance and formatting of HTML documents. It gives developers a lot of control over the look and feel of a website so you can create custom graphic designs. It also allows you to create various visual effects such as animations, gradients, shadows, and more.',
        level: 'Junior',
    },
    {
        id: 5,
        title: 'NodeJS',
        path: 'nodejs.png',
        description: 'Node.js is a JavaScript runtime environment that allows you to run JavaScript code outside of a web browser, e.g. on a server. Thanks to the use of the V8 engine, Node.js is very fast and efficient in executing JavaScript code. It is often used to create real-time applications such as chat rooms, online games, online auctions, and more.',
        level: 'Beginner',
    },
    {
        id: 6,
        title: 'MySQL',
        path: 'mysql.png',
        description: 'MySQL is a relational database management system that is one of the most popular systems of this type in the world. It is software that allows you to organize, store and manage large amounts of information in an orderly manner and in accordance with the principles of a relational database.',
        level: 'Beginner',
    },
    {
        id: 7,
        title: 'Framer Motion',
        path: 'framer-motion.png',
        description: 'Framer Motion is an animation and interaction library for React that allows you to create smooth and advanced animations in user interfaces. Thanks to this, in a simple way, our web applications are more attractive to the user.',
        level: 'Beginner',
    },
    {
        id: 8,
        title: 'Stripe',
        path: 'stripe.png',
        description: 'Stripe is an API that I got to know while doing one of my college projects. It allows you to introduce a payment processing system into your application initially on test data to make sure that all operations have been performed correctly.',
        level: 'Beginner',
    },
    {
        id: 9,
        title: 'Tailwind',
        path: 'tailwind.png',
        description: 'Tailwind CSS is a framework that I got to know relatively recently, but immediately fell in love with it. It can be used in a variety of projects, from small websites to large web applications. Thanks to the fact that Tailwind CSS provides ready-made classes, meaning affects the speed of creating responsive layouts.',
        level: 'Beginner',
    },
    {
        id: 10,
        title: 'And more!',
        path: 'more.png',
        description: 'In addition to the above skills, you can be sure that I am a person who constantly tries to develop and expand my skills to create better web applications.',
        level: '',
    },
];